version: '3'

services:
  db:
    image: postgres:12.0-alpine
  web:
    build: .
    command: [sh, -c, "cd app && python manage.py runserver 0.0.0.0:8000" ] 
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
